Repository pysal/mapclassify, pull requests merged in 2020-05, with the labels that each got.

#61 ENH: add greedy (topological) coloring
  ci/travis/36-latest-conda-forge.yaml
  ci/travis/37-latest-conda-forge.yaml
  ci/travis/38-latest-conda-forge.yaml
  docsrc/api.rst
  mapclassify.yml
  mapclassify/__init__.py
  mapclassify/greedy.py
  mapclassify/tests/test_greedy.py
  notebooks/Greedy_coloring.ipynb
  requirements_tests.txt
Labels: enhancement

#65 Migrate to GHA
  .github/workflows/unittests.yml
  .travis.yml
  CHANGELOG.txt
  MANIFEST.in
  README.rst
  appveyor.yml
  ci/36-numba.yaml
  ci/36.yaml
  ci/37-numba.yaml
  ci/37.yaml
  ci/38-numba.yaml
  ci/38.yaml
  codecov.yml
  readthedocs.yml
  requirements.txt
  requirements_tests.txt
  setup.py
Labels: CI, GitHub Actions

#69 Code format and README
  README.md
  mapclassify/classifiers.py
  mapclassify/datasets/__init__.py
  mapclassify/datasets/calemp/data.py
  mapclassify/greedy.py
  mapclassify/pooling.py
  mapclassify/tests/test_mapclassify.py
Labels: CI, GitHub Actions, docs, maintenance
