Repository pysal/mapclassify, pull requests merged in 2023-09, with the labels that each got.

#188 CI: test against nightlies
  .github/workflows/testing.yml
  ci/311-dev.yaml
  mapclassify/classifiers.py
  mapclassify/pooling.py
Labels: CI

#193 infrastructure modernization, etc.
  .github/workflows/build_docs.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .github/workflows/versioneer.yml
  .pre-commit-config.yaml
  MANIFEST.in
  ci/310.yaml
  ci/311-dev.yaml
  ci/311-numba.yaml
  ci/311.yaml
  ci/38-numba.yaml
  ci/39-min.yaml
  ci/39-numba.yaml
  ci/39.yaml
  docs/conf.py
  docs/installation.rst
  environment.yml
  mapclassify/__init__.py
  mapclassify/_version.py
  pyproject.toml
  requirements.txt
  requirements_docs.txt
  requirements_speedups.txt
  requirements_tests.txt
  setup.cfg
  setup.py
  versioneer.py
Labels: maintenance, infra

#195 lint code base with `ruff`
  .github/workflows/release.yml
  mapclassify/classifiers.py
  mapclassify/greedy.py
  mapclassify/pooling.py
Labels: maintenance

#196 remove 2 more superfluous files
  .coveragerc
  .pylintrc
Labels: maintenance
