Repository pysal/mapclassify, pull requests merged in 2024-07, with the labels that each got.

#216 plot histogram with class bins
  .github/workflows/testing.yml
  ci/310-numba.yaml
  ci/310.yaml
  ci/311-numba.yaml
  ci/311.yaml
  ci/312-dev.yaml
  ci/312-numba.yaml
  ci/312.yaml
  mapclassify/classifiers.py
  mapclassify/tests/baseline/test_histogram_plot.png
  mapclassify/tests/baseline/test_histogram_plot_despine.png
  mapclassify/tests/baseline/test_histogram_plot_linewidth.png
  mapclassify/tests/test_mapclassify.py
  pyproject.toml
Labels: enhancement

#211 WIP classify to rgba
  mapclassify/__init__.py
  mapclassify/tests/test_rgba.py
  mapclassify/util.py
Labels: enhancement

#224 infra update - CI, names, linting, format, etc.
  .github/workflows/build_docs.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  README.md
  ci/310-latest.yaml
  ci/310-numba-latest.yaml
  ci/310-oldest.yaml
  ci/311-latest.yaml
  ci/311-numba-latest.yaml
  ci/312-latest.yaml
  ci/312-numba-latest.yaml
  ci/39-latest.yaml
  ci/39-numba-latest.yaml
  ci/39-oldest.yaml
  docs/installation.rst
  environment.yml
  pyproject.toml
Labels: CI, infra

#227 Update README.md -- remove mention of `geoplot`
  README.md
Labels: docs
