Repository pysal/mapclassify, pull requests merged in 2025-06, with the labels that each got.

#258 remove scratch noteobok
  notebooks/07_std_anchor.ipynb
Labels: docs

#265 image testing and comparison revamping
  .github/workflows/testing.yml
  mapclassify/tests/baseline/test_histogram_plot.png
  mapclassify/tests/baseline/test_histogram_plot_despine.png
  mapclassify/tests/baseline/test_histogram_plot_linewidth.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_cmap.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_default.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_kwargs.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_map.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_position.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_quantiles.png
  mapclassify/tests/baseline_images/test_legendgram/legendgram_vlines.png
  mapclassify/tests/baseline_images/test_mapclassify/test_histogram_plot.png
  mapclassify/tests/baseline_images/test_mapclassify/test_histogram_plot_despine.png
  mapclassify/tests/baseline_images/test_mapclassify/test_histogram_plot_linewidth.png
  mapclassify/tests/conftest.py
  mapclassify/tests/test_legendgram.py
  mapclassify/tests/test_mapclassify.py
  mapclassify/tests/test_rgba.py
Labels: maintenance, CI, infra

#269 fix codecov badge rendering
  README.md
Labels: docs

#273 `cmap` detection functionality
  mapclassify/classifiers.py
  mapclassify/legendgram.py
  mapclassify/tests/baseline_images/test_legendgram/legendgram_most_recent_cmap.png
  mapclassify/tests/test_legendgram.py
  notebooks/09_legendgram.ipynb
Labels: enhancement
